// Replay equivalence, Zig against Zig (issue #5: from fuel on, the Zig kernel
// is its own reference; the TS runtime is frozen and no longer compared).
// For each store: replay its log with no wallet on the Zig kernel
// (`skein-kernel replay`, attested answers from the source's records) into
// a fresh store z1, then replay z1's log into z2, and require the two to be
// exactly the same:
//
//   - the replay reports: the runtime's log lines, the log tip, the final
//     state record;
//   - everything `skein-kernel dump` derives: the log entries, chains and
//     tips, every update (with its fuel), threads, resting threads in resume
//     order, sleepers, awaits, edges, heads, the cursor, fuel per thread and
//     in total, every record's CID, the state CID (which covers every index
//     node);
//   - `skein-kernel fuel`, the billing query;
//   - the explorer (src/dev/explore, reading the file through
//     src/runtime/index-store.ts) renders every page the same over both.
//
// Also: every step that ended (finished/errored/waiting) records its fuel,
// and a source the Zig kernel wrote itself (equiv/serve.ts; format 1) is
// reproduced exactly by its replay. A store generated by the TS runtime
// (equiv/corpus.ts) is only a log here: its own updates carry no fuel.
//
//   node --experimental-strip-types --no-warnings kernel-zig/equiv/replays.ts [--keep] <store.db>…
//
// Sources are copied first (with their -wal), never opened in place.

import { spawnSync } from "node:child_process";
import { copyFileSync, existsSync, mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { basename, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { DatabaseSync } from "node:sqlite";
import * as dagCbor from "@ipld/dag-cbor";
import { CID } from "multiformats/cid";
import { openStoreFile } from "../../src/runtime/index-store.ts";
import { render } from "../../src/dev/explore/server.ts";
import { load } from "../../src/dev/explore/view.ts";

const here = dirname(fileURLToPath(import.meta.url));
const kernel = process.env.SKEIN_KERNEL ?? join(here, "../zig-out/bin/skein-kernel");
const args = process.argv.slice(2);
const keep = args.includes("--keep");
const sources = args.filter((a) => a !== "--keep");

type Dump = {
  state: string; cursor: number; log: string | null; roots: Record<string, string | null>;
  entries: unknown[]; chains: Array<[string, string, number, string | null]>; updates: Array<[string, number, string, number | null]>;
  threads: string[]; resting: string[]; sleepers: unknown[]; awaits: unknown[]; edges: unknown[]; heads: unknown[];
  fuel: { total: number; threads: Array<[string, number, number]> }; blocks: string[]; indexBlocks: number;
};
const KEYS = ["state", "cursor", "log", "roots", "entries", "chains", "updates", "threads", "resting", "sleepers", "awaits", "edges", "heads", "fuel", "blocks", "indexBlocks"] as const;

function run(cmd: string[]): { status: number | null; stdout: string; stderr: string } {
  const r = spawnSync(kernel, cmd, { maxBuffer: 1 << 30 });
  return { status: r.status, stdout: r.stdout.toString(), stderr: r.stderr.toString() };
}
function dump(db: string): Dump {
  const r = run(["dump", db]);
  if (r.status !== 0) throw new Error(`skein-kernel dump ${db}: ${r.stderr}`);
  return JSON.parse(r.stdout);
}
function fuelReport(db: string): string {
  const r = run(["fuel", db]);
  if (r.status !== 0) throw new Error(`skein-kernel fuel ${db}: ${r.stderr}`);
  return r.stdout;
}

/** The first difference between two dumps, key by key. */
function dumpDiff(x: Dump, y: Dump, what: string): string[] {
  const out: string[] = [];
  for (const k of KEYS) {
    const a = JSON.stringify(x[k]), b = JSON.stringify(y[k]);
    if (a === b) continue;
    if (Array.isArray(x[k]) && Array.isArray(y[k])) {
      const xs = (x[k] as unknown[]).map((r) => JSON.stringify(r)), ys = (y[k] as unknown[]).map((r) => JSON.stringify(r));
      const i = xs.findIndex((r, j) => r !== ys[j]);
      const at = i >= 0 ? i : Math.min(xs.length, ys.length);
      out.push(`${what} ${k}: ${xs.length} vs ${ys.length}, first difference at ${at}\n    ${xs[at]}\n    ${ys[at]}`);
    } else out.push(`${what} ${k}: ${a.slice(0, 200)} vs ${b.slice(0, 200)}`);
  }
  return out;
}

/** Every explorer page over the two files; the first that differs, if any. */
async function explorerDiff(p: string, q: string): Promise<string | undefined> {
  const x = openStoreFile(p, { readOnly: true }), y = openStoreFile(q, { readOnly: true });
  try {
    if (!("state" in x) || !("state" in y)) return "explorer: a Zig store did not open through the index";
    const w = await load(x);
    const pages = ["/", "/log", "/s", "/threads", "/h/main"];
    for (const t of w.threads) pages.push(`/t/${t.cid}`, `/r/${t.cid}`, ...t.updates.map(({ cid }) => `/r/${cid}`));
    for (const { cid } of w.log) pages.push(`/e/${cid}`);
    for (const pg of pages) {
      const a = await render(x, new URL(pg, "http://x")), b = await render(y, new URL(pg, "http://x"));
      if (a.status !== b.status || a.body !== b.body) return `explorer: ${pg} differs (status ${a.status} vs ${b.status})`;
      if (a.status >= 500) return `explorer: ${pg} fails (${a.status})`;
    }
    explorerPages += pages.length;
    return undefined;
  } finally { await x.close(); await y.close(); }
}
let explorerPages = 0;

/** A file the Zig kernel wrote in the current format (its state record has `format`). */
function isZigStore(db: string): boolean {
  const d = new DatabaseSync(db, { readOnly: true });
  try {
    const t = d.prepare("SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'pointers'").get();
    if (!t) return false;
    if (!d.prepare("SELECT 1 FROM pointers WHERE name = 'state'").get() || run(["fuel", db]).status !== 0) return false;
    // A step with fuel; or no thread at all (#51: entries nothing is subscribed to — recorded, nothing ran).
    const x = dump(db);
    return x.updates.some((u) => u[3] !== null) || !x.chains.some((c) => c[3] === "thread");
  } finally { d.close(); }
}

let allSame = true;
for (const source of sources) {
  const work = mkdtempSync(join(tmpdir(), "skein-kz-replay-"));
  const src = join(work, "src.db");
  copyFileSync(source, src);
  if (existsSync(`${source}-wal`)) copyFileSync(`${source}-wal`, `${src}-wal`);
  { const d = new DatabaseSync(src); d.exec("PRAGMA wal_checkpoint(TRUNCATE)"); d.close(); }
  const z1 = join(work, "z1.db"), z2 = join(work, "z2.db");
  const name = `${basename(dirname(source))}/${basename(source)}`;

  let t0 = Date.now();
  const r1 = run(["replay", src, z1]);
  const ms1 = Date.now() - t0;
  t0 = Date.now();
  const r2 = r1.status === 0 ? run(["replay", z1, z2]) : r1;
  const ms2 = Date.now() - t0;
  if (r1.status !== 0 || r2.status !== 0) {
    allSame = false;
    process.stdout.write(`${name}: FAILED to replay (exit ${r1.status}, ${r2.status})\n${r1.stderr}\n${r2.stderr}\n`);
    continue;
  }
  const j1 = JSON.parse(r1.stdout), j2 = JSON.parse(r2.stdout);
  const d1 = dump(z1), d2 = dump(z2);
  const diffs: string[] = [];
  for (const k of ["lines", "state"] as const) if (JSON.stringify(j1[k]) !== JSON.stringify(j2[k])) diffs.push(`replay ${k} differ: ${JSON.stringify(j1[k]).slice(0, 300)} vs ${JSON.stringify(j2[k]).slice(0, 300)}`);
  if (j1.index.record !== j2.index.record) diffs.push(`state record: ${j1.index.record} vs ${j2.index.record}`);
  if (j1.index.record !== d1.state) diffs.push(`state record: the replay ended at ${j1.index.record}, the store holds ${d1.state}`);
  for (const l of [...j1.lines, ...j2.lines] as string[]) if (/DIVERGED|cannot run/.test(l)) { diffs.push(`replay: ${l}`); break; }
  diffs.push(...dumpDiff(d1, d2, "z1 vs z2"));
  if (fuelReport(z1) !== fuelReport(z2)) diffs.push("skein-kernel fuel differs");
  // Every step that ended records its fuel (thread chains; heads and subscriptions have none).
  const threadChains = new Set(d1.chains.filter((c) => c[3] === "thread").map((c) => c[0]));
  const missing = d1.updates.filter((u) => threadChains.has(u[0]) && u[3] === null);
  const ending = d1.updates.filter((u) => threadChains.has(u[0]) && u[3] !== null).length;
  // Only a `running` update (a step starting) carries no fuel.
  const running = missing.length;
  let exhausted = 0;
  {
    const d = new DatabaseSync(z1, { readOnly: true });
    type Rec = { state?: string; fuel?: number; error?: { kind: string; message: string }; genesis?: CID; defaults?: Record<string, string> };
    const block = (c: string | CID): Rec | undefined => {
      const row = d.prepare("SELECT bytes FROM blocks WHERE cid = ?").get((typeof c === "string" ? CID.parse(c) : c).bytes);
      return row ? dagCbor.decode(row.bytes as Uint8Array) as Rec : undefined;
    };
    for (const u of missing) {
      const st = block(u[2])?.state;
      if (st !== "running") { diffs.push(`update ${u[2]} (${st}) records no fuel`); break; }
    }
    // A step that ran out: errored, can't-do "fuel exhausted", its fuel the genesis's limit.
    const g = block(block((d1.entries[0] as [number, string])[1])!.genesis!);
    const limit = Number(g?.defaults?.fuelPerStep ?? 1e12);
    for (const u of d1.updates) {
      if (!threadChains.has(u[0]) || u[3] === null) continue;
      const r = block(u[2])!;
      if (r.error?.message !== "fuel exhausted") continue;
      exhausted++;
      if (r.state !== "errored" || r.error.kind !== "cant-do" || r.fuel !== limit) diffs.push(`update ${u[2]}: fuel exhausted but ${r.state}/${r.error.kind}, fuel ${r.fuel} (limit ${limit})`);
    }
    if (/fuel\.db$/.test(basename(source)) && exhausted === 0) diffs.push(`no step ran out of fuel (limit ${limit})`);
    d.close();
  }
  const pageDiff = await explorerDiff(z1, z2);
  if (pageDiff) diffs.push(pageDiff);
  let fromSource = "";
  if (isZigStore(src)) {
    const ds = dump(src);
    const sd = dumpDiff(ds, d1, "source vs replay");
    diffs.push(...sd);
    fromSource = sd.length ? "" : " · the source store reproduced exactly";
  }
  const n = d1.entries.length;
  const counts = `${n} entries, ${d1.chains.length} chains, ${d1.updates.length} updates (${ending} with fuel, ${running} running${exhausted ? `, ${exhausted} out of fuel` : ""}), ${d1.blocks.length} blocks + ${d1.indexBlocks} index, ${j1.lines.length} lines; fuel ${d1.fuel.total}`;
  // A store with no thread ran no step: only its genesis (a mailbox nothing was delivered to: a handshake writes
  // nothing, #40), or entries nothing is subscribed to (#51: accepted libp2p messages, recorded, nothing runs).
  if (ending === 0 && threadChains.size > 0) diffs.push("no update records fuel");
  if (diffs.length) {
    allSame = false;
    process.stdout.write(`${name}: DIFFERENT (${counts})\n  ${diffs.join("\n  ")}\n`);
  } else {
    process.stdout.write(`${name}: identical (${counts}; ${ms1} ms, ${ms2} ms)${fromSource}\n`);
  }
  if (keep) process.stdout.write(`  kept ${work}\n`); else rmSync(work, { recursive: true, force: true });
}
process.stdout.write(`explorer: ${explorerPages} pages identical over the two replays' files\n`);
process.exit(allSame ? 0 : 1);
