// Write a fresh dev key to an env file (PRIVATE_KEY_WIF=…, mode 0600) unless it
// exists. Prints only the identity (public) key. Dev keys: no funds, throwaway.
import { PrivateKey } from "@bsv/sdk";
import { existsSync, readFileSync, writeFileSync } from "node:fs";

const file = process.argv[2];
if (!file) { console.error("usage: genkey.ts <env-file>"); process.exit(2); }
if (!existsSync(file)) {
  const wif = PrivateKey.fromRandom().toWif();
  writeFileSync(file, `# dev key generated by skein scripts/host/genkey.ts on ${new Date().toISOString()}; no funds\nPRIVATE_KEY_WIF=${wif}\n`, { mode: 0o600 });
}
const m = /^PRIVATE_KEY_WIF=(\S+)/m.exec(readFileSync(file, "utf8"));
if (!m) { console.error(`${file}: no PRIVATE_KEY_WIF`); process.exit(1); }
console.log(PrivateKey.fromWif(m[1]).toPublicKey().toString());
